apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    # Instruct Knative Serving to use a custom domain you own
    # Make sure to replace `starter-kit.online` with your own domain name
    domain:
      starter-kit.online: ""
