# `doks-ci-cd-tekton-triggers-sa` service account - allows Tekton EventListeners to instantiate Pipeline resources


apiVersion: v1
kind: ServiceAccount
metadata:
  name: doks-ci-cd-tekton-triggers-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: doks-ci-cd-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: doks-ci-cd-tekton-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: doks-ci-cd-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: doks-ci-cd-tekton-triggers-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
